part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const INTRO_V_C = _Paths.INTRO_V_C;
  static const SPLASH = _Paths.SPLASH;
  static const CREATE_PASSWORD = _Paths.CREATE_PASSWORD;
  static const FORGET_PASSWORD = _Paths.FORGET_PASSWORD;
  static const OTP = _Paths.OTP;
  static const LOGIN = _Paths.LOGIN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const SIGN_UP_INFO = _Paths.SIGN_UP_INFO;
  static const CHECKOUT_SHIPPING = _Paths.CHECKOUT_SHIPPING;
  static const CHECKOUT_CONGRATULATION = _Paths.CHECKOUT_CONGRATULATION;
  static const CHECKOUT_INFORMATION = _Paths.CHECKOUT_INFORMATION;
  static const CHECKOUT_PAYMENT = _Paths.CHECKOUT_PAYMENT;
  static const MY_CART = _Paths.MY_CART;
  static const ALL_PRODUCT = _Paths.ALL_PRODUCT;
  static const ALL_REVIEW = _Paths.ALL_REVIEW;
  static const SEE_CATEGORIES = _Paths.SEE_CATEGORIES;
  static const MENU_SCREEN = _Paths.MENU_SCREEN;
  static const OFFER_ROLE_SCREEN = _Paths.OFFER_ROLE_SCREEN;
  static const DETAIL_SCREEN = _Paths.DETAIL_SCREEN;
  static const REQUEST_QUOTE_SCREEN = _Paths.REQUEST_QUOTE_SCREEN;
  static const ACCOUNT_INFORMATION_SCREEN = _Paths.ACCOUNT_INFORMATION_SCREEN;
  static const ADD_NEW_ADDRESS_SCREEN = _Paths.ADD_NEW_ADDRESS_SCREEN;
  static const ADDRESS_BOOK_SCREEN = _Paths.ADDRESS_BOOK_SCREEN;
  static const CONTACTUS_SCREEN = _Paths.CONTACTUS_SCREEN;
  static const GENERAL_SETTING = _Paths.GENERAL_SETTING;
  static const SETTING = _Paths.SETTING;
  static const MY_ORDER_SCREEN = _Paths.MY_ORDER_SCREEN;
  static const NOTIFICATION_SCREEN = _Paths.NOTIFICATION_SCREEN;
  static const POLICY_SCREEN = _Paths.POLICY_SCREEN;
  static const POLICY_CONDITION = _Paths.POLICY_CONDITION;
  static const PROFILE_SCREEN = _Paths.PROFILE_SCREEN;
  static const TERMS_CONDITION_SCREEN = _Paths.TERMS_CONDITION_SCREEN;
  static const FORGET_PASSWORD_OTP_SCREEN = _Paths.FORGET_PASSWORD_OTP_SCREEN;
  static const NOTIFICATION_LIST_SCREEN = _Paths.NOTIFICATION_LIST_SCREEN;
  static const BOTTOM_TAP = _Paths.BOTTOM_TAP;
  static const DASHBORD_S = _Paths.DASHBORD_S;
  static const ORDER_S = _Paths.ORDER_S;
  static const DELIVERY_S = _Paths.DELIVERY_S;
  static const ADDRESSBOOK_SCREEN = _Paths.ADDRESSBOOK_SCREEN;
  static const BILLS_SCREEN = _Paths.BILLS_SCREEN;
  static const CREDIT_NOTES_SCREEN = _Paths.CREDIT_NOTES_SCREEN;
  static const DEALMAKER_SCREEN = _Paths.DEALMAKER_SCREEN;
  static const NEEDHELP_SCREEN = _Paths.NEEDHELP_SCREEN;
  static const DASHBORD_B2B = _Paths.DASHBORD_B2B;
  static const ORDER_B2B_SCREEN = _Paths.ORDER_B2B_SCREEN;
  static const OFFER_B2B_SCREEN = _Paths.OFFER_B2B_SCREEN;
  static const NEEDHELP_S = _Paths.NEEDHELP_S;
  static const LEGAL = _Paths.LEGAL;
  static const DELIVERY_CONDITION = _Paths.DELIVERY_CONDITION;
  static const ALL_CATEGORY = _Paths.ALL_CATEGORY;
  static const SPARE_PART_SCREEN = _Paths.SPARE_PART_SCREEN;
  static const B2B_SHOP_SCREEN = _Paths.B2B_SHOP_SCREEN;
  static const B2B_SHOP_ADMIN_SCREEN = _Paths.B2B_SHOP_ADMIN_SCREEN;


}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const INTRO_V_C = '/intro-v-c';
  static const SPLASH = '/splash';
  static const CREATE_PASSWORD = '/create-password';
  static const FORGET_PASSWORD = '/forget-password';
  static const OTP = '/otp';
  static const LOGIN = '/login';
  static const SIGN_UP = '/sign-up';
  static const EDIT_PROFILE = '/editProfile';
  static const SIGN_UP_INFO = '/sign-up-info';
  static const CHECKOUT_SHIPPING = '/checkout-shipping';
  static const CHECKOUT_CONGRATULATION = '/checkout-congratulation';
  static const CHECKOUT_INFORMATION = '/checkout-information';
  static const CHECKOUT_PAYMENT = '/checkout-payment';
  static const MY_CART = '/my-cart';
  static const ALL_PRODUCT = '/all-product';
  static const ALL_REVIEW = '/all-review';
  static const SEE_CATEGORIES = '/see-categories';
  static const MENU_SCREEN = '/menu-screen';
  static const OFFER_ROLE_SCREEN = '/offer-role-screen';
  static const DETAIL_SCREEN = '/detail-screen';
  static const REQUEST_QUOTE_SCREEN = '/request-quote-screen';
  static const ACCOUNT_INFORMATION_SCREEN = '/account-information-screen';
  static const ADD_NEW_ADDRESS_SCREEN = '/add-new-address-screen';
  static const ADDRESS_BOOK_SCREEN = '/address-book-screen';
  static const CONTACTUS_SCREEN = '/contactus-screen';
  static const GENERAL_SETTING = '/general-setting';
  static const SETTING = '/setting';
  static const MY_ORDER_SCREEN = '/my-order-screen';
  static const NOTIFICATION_SCREEN = '/notification-screen';
  static const POLICY_SCREEN = '/policy-screen';
  static const POLICY_CONDITION = '/policy-condition';
  static const PROFILE_SCREEN = '/profile-screen';
  static const TERMS_CONDITION_SCREEN = '/terms-condition-screen';
  static const FORGET_PASSWORD_OTP_SCREEN = '/forget-password-otp-screen';
  static const NOTIFICATION_LIST_SCREEN = '/notification-list-screen';
  static const BOTTOM_TAP = '/bottom-tap';
  static const DASHBORD_S = '/Dashbord-b2b';
  static const ORDER_S = '/order-b2b';
  static const DELIVERY_S = '/delivery-notes-b2b';
  static const ADDRESSBOOK_SCREEN = '/addressbook-supplier-screen';
  static const BILLS_SCREEN = '/bills-supplier-screen';
  static const CREDIT_NOTES_SCREEN = '/creditnotes-supplier-screen';
  static const DEALMAKER_SCREEN = '/dealmaker-supplier-screen';
  static const NEEDHELP_SCREEN = '/needhelp-supplier-screen';
  static const DASHBORD_B2B = '/dashbord-supplier-screen';
  static const ORDER_B2B_SCREEN = '/order-supplier-screen';
  static const OFFER_B2B_SCREEN = '/offer-supplier-screen';
  static const NEEDHELP_S = '/needhelp-b2b-screen';
  static const LEGAL = '/legal';
  static const DELIVERY_CONDITION = '/delivery-condition';
  static const ALL_CATEGORY = '/all_category';
  static const SPARE_PART_SCREEN = '/spare-part-screen';
  static const B2B_SHOP_SCREEN = '/b2b-shop-screen';
  static const B2B_SHOP_ADMIN_SCREEN = '/b2b-shop-admin-screen';

}
